//! Tagged URN - Flat tag-based identifier system
//!
//! This library provides the fundamental tagged URN system with flat tag-based
//! naming, wildcard support, and specificity comparison.
//!
//! What two URNs mean to each other — refinement, equivalence, comparability,
//! specificity — is decided by code generated from the proved model in
//! `../formal` (Lean), not written here: see [`formal`].

pub mod tagged_urn;

/// The proved model's executable surface, generated by `lungo generate` (see
/// `../lungo.toml`) from `../formal` and checked in. Not a stable interface: the stable one is
/// [`TaggedUrn`]'s methods, and [`FormalUrn`] for crates whose own generated
/// code shares the URN type.
#[doc(hidden)]
#[allow(warnings, clippy::all, non_snake_case, non_camel_case_types, non_upper_case_globals)]
pub mod formal {
    include!("generated/tagged_urn_formal/tagged_urn_formal.rs");
}

pub use tagged_urn::*;
